### ISSUE TITLE
how to debug

### ISSUE THREAD

**Issue by mysiki** [ArtyMaury/template-finder#4]
Hey guy, I try to use this extension since many time, but it definitely not work in my setup .. How I can find log about execution for debug my problem ? 

I use it in potable version with multiroot folder and many root folder... 

So, can you say me how I can check what the extention doing ? logs ? etc 

Br,

**Comment by mysiki** [comment]
google help me :) And I have some error in logs. Have you any idea ? 
```
undefined
	at Object.extraireVarsFiles (c:\MyDoc\KEY\MyDoc\PORTABLEAPP\PortableApps\VisualStudioCodeportable\data\extensions\artymaury.template-finder-1.1.1\out\template_parser.js:69:74)
	at exports.default.parseFileForVariables.Promise.resolve.then.yamlObject (c:\MyDoc\KEY\MyDoc\PORTABLEAPP\PortableApps\VisualStudioCodeportable\data\extensions\artymaury.template-finder-1.1.1\out\template_parser.js:53:41)
```

**Comment by ArtyMaury** [comment]
Hi,
The error seems to be in a new feature that I patched since then. Could you try to update and check if the error is still here and the same ?

**Comment by mysiki** [comment]
Yes, I juste check that you have path something. I will update it and come back.

**Comment by mysiki** [comment]
Yeah !!! It's work ! I have disabled it since few month but with your last fix it's ok for me. Thx for this job !
